export const GETSTARTED = 'Get Started';
export const SIGNIN = 'Sign In';
export const WATCHLIST = 'Watch List';
export const ADDNEWWATCHLIST = 'Add New Watch List';
export const TAB = 'Tab';
export const HOME = 'Home';
export const NEWHOT = 'New & Hot';
export const SEARCH = 'Search';
export const DOWNLOADS = 'Downloads';
